openapi: 3.2.0
info:
  title: Bench Shared Filters API
  description: 'Versioning


    The API is currently at version 1.0.'
  version: '1.0'
servers:
- url: https://bench.gobridgit.com
  description: Bridgit Bench production
security:
- {}
tags:
- name: SharedFilters
paths:
  /rp/api/v1/accounts/{accountId}/shared-filters/{id}:
    delete:
      tags:
      - SharedFilters
      summary: Delete a shared filter from the given account
      description: 'Permissions

        Account: Write'
      operationId: SharedFilters_Delete
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: id
        in: path
        description: Id of the filter to remove
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  securitySchemes:
    Bearer:
      type: http
      description: Standard Authorization header using the Bearer scheme
      scheme: bearer
      bearerFormat: JWT
