openapi: 3.2.0
info:
  title: Bench Project Groupings API
  description: 'Versioning


    The API is currently at version 1.0.'
  version: '1.0'
servers:
- url: https://bench.gobridgit.com
  description: Bridgit Bench production
security:
- {}
tags:
- name: ProjectGroupings
paths:
  /rp/api/v1/accounts/{accountId}/projects/{projectId}/groupings:
    post:
      tags:
      - ProjectGroupings
      summary: Set grouping to the project in the given account
      description: 'Permissions

        Project: Write'
      operationId: ProjectGroupings_Set
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The Project ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: The IDs of grouping for setting to project
        content:
          application/json:
            schema:
              minItems: 1
              type: array
              items:
                type: integer
                format: int64
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '503':
          description: Service Unavailable
    put:
      tags:
      - ProjectGroupings
      summary: Update grouping to the project in the given account
      description: 'Permissions

        Project: Write'
      operationId: ProjectGroupings_Put
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The Project ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: The IDs of grouping for setting to project
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '503':
          description: Service Unavailable
  /rp/api/v1/accounts/{accountId}/projects/{projectId}/groupings/{id}:
    delete:
      tags:
      - ProjectGroupings
      summary: Removes grouping from the project in the given account
      description: 'Permissions

        Project: Write'
      operationId: ProjectGroupings_Remove
      parameters:
      - name: accountId
        in: path
        description: The Account ID
        required: true
        schema:
          type: integer
          format: int32
      - name: projectId
        in: path
        description: The Project ID
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: The grouping ID for project
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '503':
          description: Service Unavailable
components:
  securitySchemes:
    Bearer:
      type: http
      description: Standard Authorization header using the Bearer scheme
      scheme: bearer
      bearerFormat: JWT
